Get students
daphneaugier/kimsquit pull request #26
Opened 2019-11-29 02:56 UTC by david-ron

we need students for front end

2019-11-29 03:34 UTC, bit172 approved these changes
Looks good. Bet

2019-11-29 05:54 UTC, leojrsilao approved these changes
bet

2019-11-29 05:55 UTC, bit172 requested changes

2019-11-29 05:55 UTC, bit172 commented on src/main/java/com/kimsquitsystem/kimsquitdemo/dao/StudentDao.java
> +        final String sql = "SELECT student_id, first_name, last_name, address, group_id  FROM student WHERE user_id = ?";
student_id not user_id

2019-11-29 06:06 UTC, david-ron commented on src/main/java/com/kimsquitsystem/kimsquitdemo/dao/StudentDao.java
> +        final String sql = "SELECT student_id, first_name, last_name, address, group_id  FROM student WHERE user_id = ?";
okk

2019-11-29 06:11 UTC, david-ron commented on src/main/java/com/kimsquitsystem/kimsquitdemo/dao/StudentDao.java
> +        final String sql = "SELECT student_id, first_name, last_name, address, group_id  FROM student WHERE user_id = ?";
done

2019-11-29 06:27 UTC, bit172 approved these changes

2019-11-29 06:28 UTC, merged

2019-11-30 06:27 UTC, bit172 commented
#8